config/routes.rb
Rails.application.routes.draw do
  root 'flappy_clone#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 15 },  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flappy_clone_controller.rb
class FlappyCloneController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path unless session[:user_id].nil?
  end

  def create
    user = User.find_by_name(params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash.now[:success] = "Logged in successfully."
    else
      flash.now[:alert] = "Wrong username and/or password."
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    session[:user_id] = nil
    flash.now[:success] = "Logged out successfully."
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully created account."
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def float_arr2string(n)
    n.map{ |a| a.to_s }.join(" ")
  end

  def string2float_arr(s)
    n.split(" ").map{ |a| a.to_f }
  end

  def highest_score(s)
    string2float_arr(s)[0]
  end
end

app/helpers/flappy_clone_helper.rb
module FlappyCloneHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flappy_clone/index.html.slim
marquee
  h1 asdf

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to "Flappy Bird Clone", root_path, class: "navbar-brand"
    ul.nav.navbar-nav.navbar-right
      - if current_user.nil?
        li
          = link_to "Sign Up", signup_path
      - else
        li
          .signed-in-as
            | Signed in as 
            strong #{current_user.name}
        li
          = link_to "Log Out", logout_path, remote: true
    - if current_user.nil?
      = simple_form_for(:session, url: login_path, html: { class: 'navbar-form navbar-right' }, remote: true) do |f|
        .form-group
          = f.input :name, required: true, label: false, placeholder: 'User Name', input_html: { class: 'form-control input-xs' }
          = f.input :password, required: true, label: false, placeholder: 'Password', input_html: { class: 'form-control input-xs' }
          = f.button :submit, 'Log In', class: 'btn-primary input-xs'
    ul.nav.navbar-nav.navbar-right.nav-alert
      - flash.each do |name, msg|
        li
          .navbar-alert class="#{alert_for(name)}"
            = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    title NeuroEvolve
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #navbar
      = render 'layouts/navbar'
    == yield

app/views/users/new.html.slim
.col-md-4.col-md-offset-0
  .center-block
    h2 Sign Up
    = simple_form_for(@user, url: signup_path, html: { class: 'form-horizontal' }) do |f|
      .panel-body
        = f.error_notification
        = f.input :name, required: true, label: false, placeholder: 'User Name', input_html: { class: 'form-control' }
        = f.input :password, required: true, label: false, placeholder: 'Password', input_html: { class: 'form-control' }
        = f.input :password_confirmation, required: true, label: false, placeholder: 'Confirm Password', input_html: { class: 'form-control' }
      = f.button :submit, class: 'btn btn-primary'